### PR TITLE
Added computation of best perfectWidth with kmeans algo

### PR DESCRIPTION
**Pull request by welcoMattic**
This PR attempts to bring the computation of perfectWidth (= ideal image width depending on the viewport popularity) with k-means algo.

It seems working for a testing project, but I'm not 100% sure of this.

Ref #14

### CODE REVIEW

**Comment by nhoizey** [comment]
@welcoMattic now that I managed to upgrade all dependencies to current versions (apart from `csv-parse`: #391 ), could you try to update your PR?

There are many conflicts in package files, I'm not sure own to deal with this without breaking things. 😞

Thanks

**Comment by welcoMattic** [comment]
Hi @nhoizey, the branch is rebased. TBH, I don't remember very well how this works, but I fixed the tests.

**Comment by nhoizey** [comment]
@welcoMattic thanks! 🙏

I'll try to check and test this week.

**Comment by nhoizey** [comment]
@welcoMattic I just checked, I get a result that looks fine! 👍

I will merge the PR, as it will be at least a good start, and we'll be able to fine tune after.

Thanks a lot, and sorry again for the way too long delay to merge this. 🙏

**Pull request merged**
